<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.3 setup script
 * Date: Fri, 19 Oct 2012 10:29:04 +0400
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '/var/run/mysql/mysql.sock';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'musql_user';
$cfg['Servers'][$i]['password'] = 'mysql_password';
$cfg['Servers'][$i]['AllowRoot'] = false;
$cfg['Servers'][$i]['CountTables'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = '5080f1f05c79a3.76467040';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['AllowUserDropDatabase'] = true;
$cfg['McryptDisableWarning'] = true;
$cfg['LeftDisplayLogo'] = false;
$cfg['LeftDisplayServers'] = true;
$cfg['DisplayServersList'] = true;
$cfg['DisplayDatabasesList'] = 0;
$cfg['ShowPhpInfo'] = true;
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
?>