Vagrant.configure(2) do |config|
  config.vm.box = "gwinn/jessie64-lnmp-lxc"
  config.vm.hostname = "lamp-lxc"
  config.vm.synced_folder "/home/gwinn/Documents/Sources/php", "/source"
  config.vm.network "forwarded_port", guest: 80, host: 8999
  config.vm.provider :lxc do |lxc|
    lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
    lxc.customize 'network.link', 'virbr0'
    lxc.customize 'network.ipv4', '0.0.0.0/24'
  end
end
